import { defineConfig } from "vite";

export default defineConfig({
  base: "./",  // relative paths so the site works under any subdirectory (e.g. GitHub Pages /veloanalyzer/)
  build: {
    outDir: "../docs",
    emptyOutDir: false,  // preserve data.db written by Python
    rollupOptions: {
      input: "app.html",
      output: {
        // Content-hashed JS filenames so browsers can't serve a stale cached
        // bundle after a rebuild — app.html is regenerated by Vite each build
        // with the correct reference, so no other file needs to know the name.
        entryFileNames: "app-[hash].js",
        chunkFileNames: "app-[hash].js",
        // index.css is referenced by static, non-Vite-managed pages
        // (index.html, races.html) so its name must stay fixed.
        assetFileNames: (info) => info.name?.endsWith(".css") ? "index.css" : "[name][extname]",
      },
    },
  },
  optimizeDeps: {
    exclude: ["sql.js"],
  },
  // sql.js needs its WASM file served as a static asset
  assetsInclude: ["**/*.wasm"],
});
