import { defineConfig } from "vite";

export default defineConfig({
  base: "./",  // relative paths so the site works under any subdirectory (e.g. GitHub Pages /veloanalyzer/)
  build: {
    outDir: "../docs",
    emptyOutDir: false,  // preserve data.db written by Python
    rollupOptions: {
      // All three pages are Vite entries now. index.html and races.html used to
      // be written by scripts/generate_site.py from scraped data; they render
      // from the API instead, so nothing needs a build-time database.
      input: {
        index: "index.html",
        app:   "app.html",
        races: "races.html",
      },
      output: {
        // Content-hashed filenames so browsers can't serve a stale cached
        // bundle after a rebuild — each HTML file is regenerated by Vite with
        // the correct reference, so nothing else needs to know the name.
        entryFileNames: "[name]-[hash].js",
        chunkFileNames: "chunk-[hash].js",
        assetFileNames: (info) => info.name?.endsWith(".css") ? "index.css" : "[name][extname]",
      },
    },
  },
});
