"""Baseline schema.

Built from mtb_analyzer/schema.py rather than hand-transcribed columns, so the
metadata stays the single source of truth for the initial shape. Later
revisions are ordinary autogenerated op.* calls.

Revision ID: 0001_initial
Revises:
"""

import sqlalchemy as sa
from alembic import op

from mtb_analyzer.schema import metadata

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    # Required by the gin_trgm_ops index on riders.normalized_name.
    bind.execute(sa.text("CREATE EXTENSION IF NOT EXISTS pg_trgm"))
    metadata.create_all(bind)


def downgrade() -> None:
    metadata.drop_all(op.get_bind())
