#!/usr/bin/env python3
"""
Reads races.yml and generates one HTML report per race into docs/,
then writes a docs/index.html landing page linking to all reports.
"""

import os
import sys
from datetime import datetime

import yaml

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from mtb_analyzer.config import console
from mtb_analyzer.export import export_html
from mtb_analyzer.parsers import parse_start_list
from mtb_analyzer.ranking import fetch_rider_history, get_uci_cache, lookup_rider

REPO_ROOT  = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RACES_FILE = os.path.join(REPO_ROOT, "races.yml")
DOCS_DIR   = os.path.join(REPO_ROOT, "docs")


def load_races() -> list:
    with open(RACES_FILE, encoding="utf-8") as f:
        return yaml.safe_load(f).get("races", [])


def generate_report(race: dict, uci_caches: dict) -> bool:
    url          = race["url"]
    category     = race.get("category")
    uci_category = race.get("uci_category", "MJ")
    output_path  = os.path.join(DOCS_DIR, race["output"])

    if uci_category not in uci_caches:
        uci_caches[uci_category] = get_uci_cache(uci_category)
    cache = uci_caches[uci_category]

    console.print(f"\n[cyan]Generating:[/cyan] {race.get('name', url)}")
    riders, race_name = parse_start_list(url, category)

    if not riders:
        console.print(f"[yellow]  No riders found — skipping[/yellow]")
        return False

    console.print(f"[green]  ✓ {len(riders)} riders[/green]")
    console.print(f"[dim]  Looking up UCI rankings and fetching race histories...[/dim]")
    for rider in riders:
        lookup_rider(rider, cache)
        if rider.xcodata_slug:
            rider.race_results = fetch_rider_history(rider.xcodata_slug)

    export_html(riders, race_name, uci_category, output_path,
                race_date=race.get("date", ""))
    return True


def generate_index(races: list, results: list):
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M UTC")
    rows = ""
    for race, ok in zip(races, results):
        status = f'<a href="{race["output"]}">{race.get("name", race["output"])}</a>' if ok \
                 else f'<span style="color:#718096">{race.get("name", race["output"])} (failed)</span>'
        date   = race.get("date", "—")
        cat    = race.get("category", "—")
        uci    = race.get("uci_category", "MJ")
        rows  += f'<tr><td>{status}</td><td>{date}</td><td>{cat}</td><td>{uci}</td></tr>\n'

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>VeloAnalyzer — Race Reports</title>
<style>
  *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    font-family: 'Segoe UI', system-ui, sans-serif;
    background: #0f1117; color: #e2e8f0;
    line-height: 1.6; padding: 3rem 1rem;
  }}
  .container {{ max-width: 800px; margin: 0 auto; }}
  h1 {{ font-size: 1.8rem; color: #90cdf4; margin-bottom: .4rem; }}
  .sub {{ color: #718096; font-size: .9rem; margin-bottom: 2.5rem; }}
  table {{ width: 100%; border-collapse: collapse; font-size: .9rem; }}
  thead tr {{ background: #2d3748; color: #a0aec0; text-transform: uppercase;
              font-size: .75rem; letter-spacing: .06em; }}
  th, td {{ padding: .6rem .9rem; text-align: left; border-bottom: 1px solid #2d3748; }}
  tbody tr:hover {{ background: #1a202c; }}
  a {{ color: #63b3ed; text-decoration: none; }}
  a:hover {{ text-decoration: underline; }}
  .footer {{ margin-top: 2.5rem; font-size: .75rem; color: #4a5568;
             border-top: 1px solid #2d3748; padding-top: 1rem; }}
</style>
</head>
<body>
<div class="container">
  <h1>🚵 VeloAnalyzer — Race Reports</h1>
  <p class="sub">UCI-enriched MTB start list analysis &nbsp;·&nbsp; Updated: {generated_at}</p>
  <table>
    <thead><tr><th>Race</th><th>Date</th><th>Category</th><th>UCI ranking</th></tr></thead>
    <tbody>
{rows}
    </tbody>
  </table>
  <div class="footer">
    Generated by <a href="https://github.com/jfulem/veloanalyzer">veloanalyzer</a>
    &nbsp;·&nbsp; Ranking data © <a href="https://www.xcodata.com">xcodata.com</a>
  </div>
</div>
</body>
</html>"""

    index_path = os.path.join(DOCS_DIR, "index.html")
    with open(index_path, "w", encoding="utf-8") as f:
        f.write(html)
    console.print(f"\n[green]✓ Index written to {index_path}[/green]")


def main():
    os.makedirs(DOCS_DIR, exist_ok=True)
    races = load_races()
    if not races:
        console.print("[yellow]No races defined in races.yml[/yellow]")
        return

    console.print(f"[bold cyan]Generating {len(races)} report(s)...[/bold cyan]")
    uci_caches = {}
    results    = [generate_report(r, uci_caches) for r in races]
    generate_index(races, results)
    console.print("\n[bold green]Done.[/bold green]")


if __name__ == "__main__":
    main()
